version: '3.9'

services:
  web:
    build: .
    container_name: bee_app
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./static/avatars:/app/static/avatars
    command: gunicorn --bind 0.0.0.0:5000 app:app

  db:
    image: postgres:15
    container_name: bee_db
    environment:
      POSTGRES_USER: damko
      POSTGRES_PASSWORD: damko      # MUST be set
      POSTGRES_DB: lab2
    restart: always


    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
